# Generated by Django 3.0.4 on 2020-07-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0007_auto_20200706_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click Link To Read Blog Post..', max_length=255),
        ),
    ]
